app/core/urls.py
from django.urls import path, include, re_path



from core import views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View
from rest_framework.schemas import get_schema_view

app_name = 'core'

urlpatterns = [

    re_path(r"^dash/$", views.DashboardView.as_view(), name="Dashboard"),
    re_path(r"^stow/$", views.StowView.as_view(), name="Stow"),
    re_path(r"^stow-create-form/$", views.StowCreateForm.as_view(), name="StowCreateForm"),
    

]


app/map/urls.py
from django.urls import path, include, re_path



from map import views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View


app_name = 'map'

urlpatterns = [
    re_path(r"^area/$", views.AreaView.as_view(), name="Area"),
    re_path(r"^area/field/$", views.FieldDetailView.as_view(), name="field_detail"),
]

app/project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.views.generic import RedirectView
from django.urls import reverse
from django.conf import settings


schema_view = get_schema_view(
   openapi.Info(
      title="API",
      default_version='v1',
      description="API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@mign.pl"),
      license=openapi.License(name="BSD License"),
      
   ),
   public=True,
   url=settings.SERVER_URL,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
   # redirect "/" to swagger
   re_path(r'^$', RedirectView.as_view(url='/core/welcome')),
    
   # admin urls
   path('accounts/', admin.site.urls),
    
   # api urls
   path('api/user/',include('user.urls')),
   path('api-auth/', include('rest_framework.urls')),
    
   # Swager urls
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

   #core urls
   path('core/', include('core.urls')),
   #map urls
   path('map/', include('map.urls')),
   path('room_equipment/', include('room_equipment.urls')),
   path('stock/', include('stock.urls')),
    
]

app/stock/urls.py
from django.urls import path, include, re_path



import core.views
import stock.views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View


app_name = 'stock'

urlpatterns = [
    re_path(r"^itemloc/search/$", stock.views.SearchItemLocationView.as_view(), name="Search_items"),
    re_path(r"^itemloc/$", stock.views.GetItemLocations.as_view(), name="GetItemLocations"),
    re_path(r"^getitems/$", stock.views.GetItems.as_view(), name="GetItems"),
    re_path(r"^getcontaineritems/$", stock.views.GetContainerItems.as_view(), name="GetContainerItems"),
]

app/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import datetime
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.core.exceptions import ValidationError, FieldError



class DefaultObject(models.Model):
    """
    Klasa obiektu deafultowego
    """
    
    name = models.CharField(_("Nazwa"), max_length=25)
    description = models.TextField(_("Opis"), blank = True)
    

    class Meta:
        verbose_name = _("DefaultObject")
        verbose_name_plural = _("DefaultObjects")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("DefaultObject_detail", kwargs={"pk": self.pk})

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """ Tworzy uzytkownika """
        if not email:
            raise ValueError('Uzytkownik musi mieć email')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,email,password):
        """ Tworzy superusera """
        user = self.create_user(email,password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    def create_staff(self,email,password):
        user = self.create_user(email,password)
        user.is_staff = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(max_length=255,unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    objects = UserManager()
    USERNAME_FIELD = 'email'

app/stock/models.py
from django.db import models

# Create your models here.
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.urls import reverse
from core.models import DefaultObject
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError, FieldError
import room_equipment.models
from django.utils.html import mark_safe

class Manufacturer(DefaultObject, models.Model):

    """
    Item Manufacturer
    """

    logo = models.ImageField(
        _("logo"), 
        upload_to='uploads/logo/manufacturer', 
        height_field=None, 
        width_field=None, 
        max_length=None,
        blank=True
        )


    class Meta:
        verbose_name = _("Manufacturer")
        verbose_name_plural = _("Manufacturers")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Manufacturer_detail", kwargs={"pk": self.pk})

    def logo_tag(self):
        if self.logo:
            return mark_safe('<img src="%s" width="50px" height="50px" />'%(self.logo.url))
        return None
    logo_tag.short_description = 'Manufacturer logo'
    logo_tag.allow_tags = True

class Item(DefaultObject, models.Model):
    """
    Item
    """
    manufacturer_fk = models.ForeignKey(
        Manufacturer, verbose_name=_("manufacturer"), on_delete=models.CASCADE,
        null=True)
    model = models.CharField(_("model"), max_length=50, blank=True)
    is_consumable = models.BooleanField(_("is_consumable"),default=False)
    icon = models.ImageField(
        _("icon"), 
        upload_to='uploads/icons/item', 
        height_field=None, 
        width_field=None, 
        max_length=None,
        blank=True
        )

    class Meta:
        verbose_name = _("Item")
        verbose_name_plural = _("Items")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("Item_detail", kwargs={"pk": self.pk})
    def icon_tag(self):
        if self.icon:
            return mark_safe('<img src="%s" width="50px" height="50px" />'%(self.icon.url))
        return None
    icon_tag.short_description = 'Item icon'
    icon_tag.allow_tags = True

class ItemLocation(models.Model):
    """
    Lokalizacja itemu
    """
    description = models.TextField(_("description"),blank=True)
    container_item_fk = models.ForeignKey(
        room_equipment.models.ContainerItem, 
        verbose_name=_("container_item"), 
        on_delete=models.CASCADE, null=True
        )
    item_fk = models.ForeignKey(Item, verbose_name=_("item"), on_delete=models.CASCADE)
    serial = models.CharField(_("serial"), max_length=50,blank=True)
    pieces = models.IntegerField(_("pieces"))
    mac = models.CharField(_("mac"), max_length=50,blank=True)
    ip = models.CharField(_("ip"), max_length=50,blank=True)


    class Meta:
        verbose_name = _("ItemLocation")
        verbose_name_plural = _("ItemLocations")

    def get_info(self):
        return f"{self.item_fk.name} x{self.pieces}"

    def __str__(self):
        return self.get_info()

    def get_absolute_url(self):
        return reverse("ItemLocation_detail", kwargs={"pk": self.pk})

app/core/forms.py
from unicodedata import name
from django.forms.models import model_to_dict
import json
from django.forms import ModelChoiceField, ModelForm
import django.forms as forms
from django.core.exceptions import ValidationError, FieldError
import map.models
import room_equipment.models
import stock.models


class PickForm(forms.Form):
    """
    Pick form
    """
    
    item_queryset = stock.models.Item.objects.all()
    area_queryset = map.models.Area.objects.all()

    item = forms.ModelChoiceField(queryset=item_queryset, empty_label="(Nothing)")
    name = forms.CharField(label="name", max_length=50, required=False)
    serial = forms.CharField(label="serial", max_length=70, required=False)
    area = forms.ModelChoiceField(queryset=area_queryset, empty_label="(Nothing)")

app/core/views.py
from webbrowser import get
from django.shortcuts import render
import json
from django.views import View
from django.http import JsonResponse
from django.shortcuts import render
import datetime
from core.models import User
from func import functions as fnc
import map.forms
import core.forms
import stock.models
from django.http import QueryDict
from django.forms.models import model_to_dict
import urllib.parse
from ast import literal_eval
from django.core import serializers
from django.db.models import Q
from rest_framework import status
import stock.forms
from django.template.loader import render_to_string
from rest_framework import status

class DashboardView(View):
    """
    Menu
    """

    template_name = "core/dashboard.html"
    
    def get_context_data(self, request, **kwargs):
        context = {}
        # context["pick_form"] = self.pick_form
        return context
    
    def get(self, request, pk=None, *args, **kwargs):

        return render(
            request, 
            template_name=self.template_name,
            context=self.get_context_data(request,**kwargs)
            )

    def post(self, request, pk=None, *args, **kwargs):

        #print(fnc.get_querydict_data(request, data_key="form_data", *args, **kwargs))
        #print(fnc.get_querydict_data(request, data_key="additional_data", *args, **kwargs))
        #print(fnc.get_dict_data(request, data_key="additional_data", *args, **kwargs))
        #print(fnc.get_eval_dict(self.get_dict_data(request, data_key="additional_data", *args, **kwargs)))
        
        return JsonResponse(data={"status": status.HTTP_202_NOT_FOUND})

class StowView(View):
    """
    Stow
    """

    template_name = "core/stow.html"


    def get_context_data(self, request, **kwargs):
        context = {}
        return context
    
    def get(self, request, pk=None, *args, **kwargs):

        return render(
            request, 
            template_name=self.template_name,
            context=self.get_context_data(request,**kwargs)
            )
 
class StowCreateForm(View):
    """
    Stow
    """

    form = stock.forms.ItemLocationForm
    form_template = "core/forms/stow-form.html"


    def get_context_data(self, request, **kwargs):
        context = {}
        context["form"] = self.form
        return context
    
    def get(self, request, pk=None, *args, **kwargs):

        return render(
            request, 
            template_name=self.form_template,
            context=self.get_context_data(request,**kwargs)
            )

    def post(self, request, pk=None, *args, **kwargs):

        json_data = fnc.get_json_data(request, data_key="form_data", *args, **kwargs)
        json_additional_data = fnc.get_json_data(request, data_key="additional_data", *args, **kwargs)
        
        form_data = fnc.get_form_querydict_data(
            request,
            data_key="form_data", #< - {"data": JSON.Stringify($data)}
            )

        form = self.form(data=form_data)

        if form.is_valid():
            form.save()
            return JsonResponse(
                data={
                    "status":status.HTTP_201_CREATED,
                    "status_html": "<span><i class='fas fa-check text-success'></i> created!</span>"
                    }
                )
        else:
            form_string_html = render_to_string(self.form_template, {'form': form}, request=request)
            return JsonResponse(
                data={
                    "status":status.HTTP_400_BAD_REQUEST, 
                    "status_html": "<span><i class='fas fa-exclamation-circle text-danger'></i> Failed to create!</span>",
                    "form_string_html":form_string_html,
                    }
                )
class SearchItemView(View):

    def get(self, request, pk=None, *args, **kwargs):

        queryset = stock.models.Item.objects.filter(
            Q(name__contains=request.GET.get("name",None)) & 
            Q(pk__in=request.GET.get("item",None))
        ).values()

        print(queryset)
        
        return JsonResponse(data={"params": request.GET, "query": list(queryset)})

app/core/templates/core/forms/stow-form.html
{% load static %}
{% load rest_framework %}

<div class="row">
    <div class="col-12 col-md-6" id="form">
        <div class="sub-subsection-item header">
            <h5><i class="fas fa-arrow-down"></i> Stow to location</h5>
        </div>
        <hr>
        <div class="sub-subsection-item content">
            <form action="{% url 'core:StowCreateForm' %}" class="ajax-single-form" method="post" submit_button_class="submit-button" id="stow-form">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name == "container_item_fk" %}
                        <div class="field-group rounded">
                            <div class="autocomplete" id="get-container-items" url="{% url 'stock:GetContainerItems' %}" target_form="#stow-form" target_field="#id_container_item_fk" target_log="#log-window">
                                <label class="rounded">&nbsp;{{ field.label }}</label> 
                                <div class="noselect">{{ field }}</div>
                                <input type="text" id="name" class="bg-light form-control" placeholder="Search for item..."></input>
                                {{ field.errors }}
                            </div>
                        </div>
                    {% elif field.name == "item_fk" %}
                        <div class="field-group rounded">
                            <div class="autocomplete" id="get-items" url="{% url 'stock:GetItems' %}" target_form="#stow-form" target_field="#id_item_fk" target_log="#log-window">
                                <label class="rounded">&nbsp;{{ field.label }}</label> 
                                <div class="noselect">{{ field }}</div>
                                <input type="text" id="name" class="bg-light form-control" placeholder="Search for item..."></input>
                                {{ field.errors }}
                            </div>
                        </div>
                    
                    {% else %}
                    <div class="field-group rounded">
                        <label class="rounded">&nbsp;{{ field.label }}</label> {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <span class="helptext">&nbsp;{{ field.help_text }}  </span>
                        {% endif %}
                    </div>             
                    {% endif %}
                {% endfor %}
            <hr>
            </form>
            <div class="mt-4 mb-4">
                <a value="Proceed" class="btn btn-sm btn-primary submit-button" form="stow-form">&nbsp;Proceed</a>             
            </div>

        </div>
    </div>

    <div class="col-12 col-md-6" id="locations">
        <div class="sub-subsection-item header">
            <h5><i class="fas fa-map-marker"></i> Locations</h5>
        </div>
        <hr>
        <div class="sub-subsection-item content"></div>
    </div>
</div>

<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
<script src="{% static 'js/jquery-ui.js' %}"></script>
<script src="{% static 'js/ajax.js' %}"></script>
<script src="{% static 'js/csrf.js' %}"></script>
<script>
    $(".ajax-single-form").DjangoSingleAjaxForm({}) 
</script>
<script>
    function ajax_load_locations(th, thi, label, value){
        console.log("Select function load_locations starting...")
        $("div#locations div.sub-subsection-item.content").LoadRemoteContent({
            url:"{% url 'stock:GetItemLocations' %}?id="+value+"&name="+label
        })
    }
    function action1(th, thi, label, value){
        console.log("Select function action1 starting...")
        console.log(th)
        console.log(thi)
        console.log(label)
        console.log(value)
    }
    $(".autocomplete#get-container-items").AutocompleteField({
        select_function: "ajax_load_locations"
    })
    $(".autocomplete#get-items").AutocompleteField({
        select_function: "ajax_load_locations"
    })
</script>