app/core/urls.py
from django.urls import path, include, re_path



from core import views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View
from rest_framework.schemas import get_schema_view

app_name = 'core'

urlpatterns = [

    re_path(r"^dash/$", views.DashboardView.as_view(), name="Dashboard"),
    re_path(r"^stow/$", views.StowView.as_view(), name="Stow"),
    re_path(r"^stow-create-form/$", views.StowCreateForm.as_view(), name="StowCreateForm"),
    

]


app/map/urls.py
from django.urls import path, include, re_path



from map import views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View


app_name = 'map'

urlpatterns = [
    re_path(r"^area/$", views.AreaView.as_view(), name="Area"),
    re_path(r"^area/field/$", views.FieldDetailView.as_view(), name="field_detail"),
]

app/project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.views.generic import RedirectView
from django.urls import reverse
from django.conf import settings


schema_view = get_schema_view(
   openapi.Info(
      title="API",
      default_version='v1',
      description="API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@mign.pl"),
      license=openapi.License(name="BSD License"),
      
   ),
   public=True,
   url=settings.SERVER_URL,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
   # redirect "/" to swagger
   re_path(r'^$', RedirectView.as_view(url='/core/welcome')),
    
   # admin urls
   path('accounts/', admin.site.urls),
    
   # api urls
   path('api/user/',include('user.urls')),
   path('api-auth/', include('rest_framework.urls')),
    
   # Swager urls
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

   #core urls
   path('core/', include('core.urls')),
   #map urls
   path('map/', include('map.urls')),
   path('room_equipment/', include('room_equipment.urls')),
   path('stock/', include('stock.urls')),
    
]

app/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
import datetime
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.core.exceptions import ValidationError, FieldError



class DefaultObject(models.Model):
    """
    Klasa obiektu deafultowego
    """
    
    name = models.CharField(_("Nazwa"), max_length=25)
    description = models.TextField(_("Opis"), blank = True)
    

    class Meta:
        verbose_name = _("DefaultObject")
        verbose_name_plural = _("DefaultObjects")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("DefaultObject_detail", kwargs={"pk": self.pk})

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """ Tworzy uzytkownika """
        if not email:
            raise ValueError('Uzytkownik musi mieć email')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    def create_superuser(self,email,password):
        """ Tworzy superusera """
        user = self.create_user(email,password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
    def create_staff(self,email,password):
        user = self.create_user(email,password)
        user.is_staff = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(max_length=255,unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    objects = UserManager()
    USERNAME_FIELD = 'email'

app/core/forms.py
from unicodedata import name
from django.forms.models import model_to_dict
import json
from django.forms import ModelChoiceField, ModelForm
import django.forms as forms
from django.core.exceptions import ValidationError, FieldError
import map.models
import room_equipment.models
import stock.models


class PickForm(forms.Form):
    """
    Pick form
    """
    
    item_queryset = stock.models.Item.objects.all()
    area_queryset = map.models.Area.objects.all()

    item = forms.ModelChoiceField(queryset=item_queryset, empty_label="(Nothing)")
    name = forms.CharField(label="name", max_length=50, required=False)
    serial = forms.CharField(label="serial", max_length=70, required=False)
    area = forms.ModelChoiceField(queryset=area_queryset, empty_label="(Nothing)")

app/core/views.py
from webbrowser import get
from django.shortcuts import render
import json
from django.views import View
from django.http import JsonResponse
from django.shortcuts import render
import datetime
from core.models import User
from func import functions as fnc
import map.forms
import core.forms
import stock.models
from django.http import QueryDict
from django.forms.models import model_to_dict
import urllib.parse
from ast import literal_eval
from django.core import serializers
from django.db.models import Q
from rest_framework import status
import stock.forms
from django.template.loader import render_to_string
from rest_framework import status

class DashboardView(View):
    """
    Menu
    """

    template_name = "core/dashboard.html"
    
    def get_context_data(self, request, **kwargs):
        context = {}
        # context["pick_form"] = self.pick_form
        return context
    
    def get(self, request, pk=None, *args, **kwargs):

        return render(
            request, 
            template_name=self.template_name,
            context=self.get_context_data(request,**kwargs)
            )

    def post(self, request, pk=None, *args, **kwargs):

        #print(fnc.get_querydict_data(request, data_key="form_data", *args, **kwargs))
        #print(fnc.get_querydict_data(request, data_key="additional_data", *args, **kwargs))
        #print(fnc.get_dict_data(request, data_key="additional_data", *args, **kwargs))
        #print(fnc.get_eval_dict(self.get_dict_data(request, data_key="additional_data", *args, **kwargs)))
        
        return JsonResponse(data={"status": status.HTTP_202_NOT_FOUND})

class StowView(View):
    """
    Stow
    """

    template_name = "core/stow.html"


    def get_context_data(self, request, **kwargs):
        context = {}
        return context
    
    def get(self, request, pk=None, *args, **kwargs):

        return render(
            request, 
            template_name=self.template_name,
            context=self.get_context_data(request,**kwargs)
            )
 
class StowCreateForm(View):
    """
    Stow
    """

    form = stock.forms.ItemLocationForm
    form_template = "core/forms/stow-form.html"


    def get_context_data(self, request, **kwargs):
        context = {}
        context["form"] = self.form
        return context
    
    def get(self, request, pk=None, *args, **kwargs):

        return render(
            request, 
            template_name=self.form_template,
            context=self.get_context_data(request,**kwargs)
            )

    def post(self, request, pk=None, *args, **kwargs):

        json_data = fnc.get_json_data(request, data_key="form_data", *args, **kwargs)
        json_additional_data = fnc.get_json_data(request, data_key="additional_data", *args, **kwargs)
        
        form_data = fnc.get_form_querydict_data(
            request,
            data_key="form_data", #< - {"data": JSON.Stringify($data)}
            )

        form = self.form(data=form_data)

        if form.is_valid():
            form.save()
            return JsonResponse(
                data={
                    "status":status.HTTP_201_CREATED,
                    "status_html": "<span><i class='fas fa-check text-success'></i> created!</span>"
                    }
                )
        else:
            form_string_html = render_to_string(self.form_template, {'form': form}, request=request)
            return JsonResponse(
                data={
                    "status":status.HTTP_400_BAD_REQUEST, 
                    "status_html": "<span><i class='fas fa-exclamation-circle text-danger'></i> Failed to create!</span>",
                    "form_string_html":form_string_html,
                    }
                )
class SearchItemView(View):

    def get(self, request, pk=None, *args, **kwargs):

        queryset = stock.models.Item.objects.filter(
            Q(name__contains=request.GET.get("name",None)) & 
            Q(pk__in=request.GET.get("item",None))
        ).values()

        print(queryset)
        
        return JsonResponse(data={"params": request.GET, "query": list(queryset)})

app/core/templates/core/base.html
{% load static %}
{% load rest_framework %}

<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}" />
    <link rel="stylesheet" href="{% static 'css/jquery-ui.theme.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/all.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>{% block title %}{% endblock %}</title>

  </head>
  <body>


    <div class="d-flex" id="wrapper">
      <!-- Sidebar-->
      <div class="border-end bg-white" id="sidebar-wrapper">
          <div class="sidebar-heading border-bottom bg-light">ISK</div>
          <div class="list-group list-group-flush">
              <a class="list-group-item list-group-item-action p-3" href="{% url 'core:Dashboard' %}">Dashboard</a>
              <a class="list-group-item list-group-item-action p-3" href="{% url 'core:Stow' %}">Stow</a>
              <a class="list-group-item list-group-item-action p-3" href="{% url 'core:Dashboard' %}">Pick</a>
              <a class="list-group-item list-group-item-action p-3" href="{% url 'core:Dashboard' %}">Transfer</a>
              <a class="list-group-item list-group-item-action p-3" href="{% url 'core:Dashboard' %}">Add new item</a>
          </div>
      </div>
      <!-- Page content wrapper-->
      <div id="page-content-wrapper">
          <!-- Top navigation-->
          <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
              <div class="container-fluid navigation-bar">
                  <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                      <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                          <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                          <li class="nav-item"><a class="nav-link" href="#!">Link</a></li>
                          <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                  <a class="dropdown-item" href="#!">Action</a>
                                  <a class="dropdown-item" href="#!">Another action</a>
                                  <div class="dropdown-divider"></div>
                                  <a class="dropdown-item" href="#!">Something else here</a>
                              </div>
                          </li>
                      </ul>
                  </div>
              </div>
          </nav>
          <!-- Page content-->
          <div class="container-fluid content">
            
            {% block content %}
            {% endblock content %}
          </div>
      </div>
  </div>

    {% comment %} {% block content %}
    {% endblock content %} {% endcomment %}


    <!-- SCRIPT -->
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <script src="{% static 'js/all.js' %}"></script>


  </body>
</html>

app/core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% load rest_framework %}
{% block title %}Dashboard{% endblock %}



{% block content %}
<div class="row subsection">
    <div class="col-12">
        <div class="subsection-item header">
        <h1>Dashboard</h1>
        </div>
        <hr>
        <div class="subsection-item content">
        <p>This is dashboard</p>
        </div>
    </div>
</div>
{% endblock content %}

app/core/templates/core/stow.html
{% extends 'core/base.html' %}
{% load static %}
{% load rest_framework %}
{% block title %}Stow{% endblock %}

{% block content %}
    <!-- CONTENT -->
        <div class="row subsection">
            <div class="col-12">
                <div class="subsection-item header">
                    <h1><i class="fas fa-arrow-down"></i> Stow</h1>
                </div>
                <hr>
                <div class="subsection-item content">
                    <!-- FORM -->
                        <div id="stow_form" class="forms" target_log="#log-window"></div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="sub-subsection-item header">
                                        <h5><i class="fas fa-terminal"></i> Logs</h5>
                                    </div>
                                    <hr>
                                <div class="sub-subsection-item content">
                                    <div id="log-window"></div>  
                                </div>
                        </div>
                    </div>
                </div>
                </div>
            </div>

            <div class="row subsection">
                <div class="col-12">   
                </div>
            </div>           
        </div>
        <!-- SCRIPTS -->
            <script src="{% static 'js/jquery-3.6.0.js' %}"></script>
            <script src="{% static 'js/jquery-ui.js' %}"></script>
            <script src="{% static 'js/ajax.js' %}"></script>
            <script src="{% static 'js/csrf.js' %}"></script>
            <script>
                $("#stow_form").LoadRemoteContent({
                    url:"{% url 'core:StowCreateForm' %}"
                })
                
            </script>
{% endblock content %}