app/map/urls.py
from django.urls import path, include, re_path



from map import views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View


app_name = 'map'

urlpatterns = [
    re_path(r"^area/$", views.AreaView.as_view(), name="Area"),
    re_path(r"^area/field/$", views.FieldDetailView.as_view(), name="field_detail"),
]

app/project/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from django.views.generic import RedirectView
from django.urls import reverse
from django.conf import settings


schema_view = get_schema_view(
   openapi.Info(
      title="API",
      default_version='v1',
      description="API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@mign.pl"),
      license=openapi.License(name="BSD License"),
      
   ),
   public=True,
   url=settings.SERVER_URL,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
   # redirect "/" to swagger
   re_path(r'^$', RedirectView.as_view(url='/core/welcome')),
    
   # admin urls
   path('accounts/', admin.site.urls),
    
   # api urls
   path('api/user/',include('user.urls')),
   path('api-auth/', include('rest_framework.urls')),
    
   # Swager urls
   re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
   re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
   re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

   #core urls
   path('core/', include('core.urls')),
   #map urls
   path('map/', include('map.urls')),
   path('room_equipment/', include('room_equipment.urls')),
   path('stock/', include('stock.urls')),
    
]

app/room_equipment/urls.py
from django.urls import path, include, re_path



from room_equipment import views
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View


app_name = 'room_equipment'

urlpatterns = [
    re_path(r"^container/$", views.ContainerDetailView.as_view(), name="container_detail"),
    re_path(r"^container_item/$", views.ContainerItemDetailView.as_view(), name="container_item_detail"),
]

app/room_equipment/forms.py
from django.forms.models import model_to_dict
import json
# from django.forms import ModelForm
import django.forms as forms
import room_equipment.models

class ContainerDetailForm(forms.ModelForm):
    
    class Meta:
        model = room_equipment.models.Container
        fields = ['name','description','container_type_fk']


    def __init__(self,*args,**kwargs):
        super(ContainerDetailForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = \
                "shadow-sm form-control"

class ContainerItemDetailForm(forms.ModelForm):
    
    class Meta:
        model = room_equipment.models.ContainerItem
        fields = ['description']


    def __init__(self,*args,**kwargs):
        super(ContainerItemDetailForm,self).__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = \
                "shadow-sm form-control"

app/room_equipment/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse
import json
from django.http import QueryDict
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.shortcuts import get_object_or_404
import map.models
import room_equipment.models
import room_equipment.forms
import stock.models
# Create your views here.
import map.forms
from func import functions as fnc



# Create your views here.
class ContainerDetailView(View):
    """ 
    
    """
    template_detail_form = "room_equipment/forms/container_detail_form.html"
    detail_form = room_equipment.forms.ContainerDetailForm
    container_item_model = room_equipment.models.ContainerItem
    container_item_detail_form = room_equipment.forms.ContainerItemDetailForm
    model = room_equipment.models.Container


    def get(self, request, pk=None, *args, **kwargs):


        pk = self.request.GET.get('pk')
        container_instance = self.model.objects.get(pk=pk)
        items_of_container = self.container_item_model.objects.filter(container_fk=container_instance) if container_instance else []
        
        print(container_instance)

        form_instances = []
        for instance in items_of_container:
            form_instances.append(self.container_item_detail_form(instance=instance))

        if request.method == "GET":
            if pk:
                return render(
                    request,
                    self.template_detail_form,
                    {
                        "detail_form":self.detail_form(instance=container_instance),
                        "container_item_detail_forms":form_instances
                    }
                )
        
        return render(
            request,
            self.template_detail_form,
            {
                "detail_form":self.detail_form(instance=container_instance),
                "container_item_detail_forms":form_instances
            }
        )

    def prepare_form_data(self,request,data_key=None,*args,**kwargs):

        data = request.POST

        for k,v in data.items():
            if k == data_key:
                data2 = json.loads(json.dumps(data.get(data_key, '')))

                return QueryDict(data2)

    def get_object(self, *args, **kwargs):

        obj = get_object_or_404(self.model, pk=self.kwargs['pk'])

        return obj

   

    def post(self, request, *args,**kwargs):

        form_data = self.prepare_form_data(
            request,
            data_key="data", #< - {"data": JSON.Stringify($data)}
            )

        instance = self.model.objects.get(pk=self.request.GET.get('pk'))
        form = self.detail_form(data=form_data,instance=instance)

        if form.is_valid():
            form.save()
            return JsonResponse(data={"status":"OK"})
        else:
            return JsonResponse(data={"status":"Failed"})




class ContainerItemDetailView(View):
    """ 
    
    """
    template_detail_form = "room_equipment/forms/container_item_detail_form.html"
    detail_form = room_equipment.forms.ContainerItemDetailForm
    model = room_equipment.models.ContainerItem

    def prepare_form_data(self,request,data_key=None,*args,**kwargs):

        data = request.POST

        for k,v in data.items():
            if k == data_key:
                data2 = json.loads(json.dumps(data.get(data_key, '')))

                return QueryDict(data2)

    def get_object(self, *args, **kwargs):

        obj = get_object_or_404(self.model, pk=self.kwargs['pk'])

        return obj

    def get(self, request, pk=None, *args, **kwargs):


        pk = self.request.GET.get('pk')
        instance = self.model.objects.get(pk=pk)
        
        
        if request.method == "GET":
            if pk:
                return render(
                    request,
                    self.template_detail_form,
                    {
                        "detail_form":self.detail_form(instance=instance)
                    }
                )
        
        return render(
            request,
            self.template_detail_form,
            {
                "detail_form":self.detail_form(instance=instance)
            }
        )

    def post(self, request, *args,**kwargs):

        form_data = self.prepare_form_data(
            request,
            data_key="data", #< - {"data": JSON.Stringify($data)}
            )

        instance = self.model.objects.get(pk=self.request.GET.get('pk'))
        form = self.detail_form(data=form_data,instance=instance)

        if form.is_valid():
            form.save()
            return JsonResponse(data={"status":"OK"})
        else:
            return JsonResponse(data={"status":"Failed"})

app/room_equipment/templates/room_equipment/forms/container_detail_form.html
{% extends 'room_equipment/base.html' %}
{% load static %}
{% load rest_framework %}

{% block content %}



<form action="{% url 'room_equipment:container_detail' %}" method="post" model="container" id="container_detail_form{{ forloop.counter0 }}" class="m-1">
  {% csrf_token %}
  {% for field in detail_form %}
  <div class="field-group rounded">
    <label class="rounded">&nbsp;{{ field.label }}</label> {{ field }}
    {{ field.errors }}
    {% if field.help_text %}
        <span class="helptext">&nbsp;{{ field.help_text }}  </span>
    {% endif %}
    </div>             
{% endfor %}
<hr>
</form>

<!-- SUBMITION -->
<div class="mt-4 mb-4">
  <a value="Zapisz" class="btn btn-sm btn-primary ajax_post" url="{% url 'room_equipment:container_detail' %}?pk={{ form.instance.pk }}" successurl="{% url 'room_equipment:container_detail' %}"  forms="#container_detail_form{{ forloop.counter0 }}">&nbsp;Zapisz</a>
</div>





{% comment %}  


{% for form in container_item_detail_forms %}

<form action="{% url 'room_equipment:container_item_detail' %}" method="post" model="containeritem" id="container_item_detail_form{{ forloop.counter0 }}" class="m-1">
  {% csrf_token %}
  {% for field in form %}
  <div class="field-group rounded">
    <label class="rounded">&nbsp;{{ field.label }}</label> {{ field }}
    {{ field.errors }}
    {% if field.help_text %}
        <span class="helptext">&nbsp;{{ field.help_text }}  </span>
    {% endif %}
    </div>             
{% endfor %}
<hr>
</form>

<!-- SUBMITION -->
<div class="mt-4 mb-4">
  <a value="Zapisz" class="btn btn-sm btn-primary ajax_post" url="{% url 'room_equipment:container_item_detail' %}?pk={{ form.instance.pk }}" successurl="{% url 'room_equipment:container_item_detail' %}"  forms="#container_item_detail_form{{ forloop.counter0 }}">&nbsp;Zapisz</a>
</div>
{% endfor %}

{% endcomment %}




{% comment %} 

<form action="{% url 'map:field_detail' %}" method="post" model="field" id="field_detail_form" class="m-1">
    {% csrf_token %}
    {% for field in detail_form %}
    <div class="field-group">
      <label>{{ field.label }}</label> {{ field }}
      {{ field.errors }}
      {% if field.help_text %}
          <span class="helptext">&nbsp;{{ field.help_text }}  </span>
      {% endif %}
      </div>             
  {% endfor %}
  </form>

  <!-- SUBMITION -->
  <div class="mt-4">
    <a value="Zapisz" class="btn btn-sm btn-primary ajax_post" url="{% url 'map:field_detail' %}" successurl="{% url 'map:field_detail' %}"  forms="#field_detail_form">&nbsp;Zapisz</a>
  </div>

{% endcomment %}

{% endblock content %}